const xml = `<?xml version="1.0" encoding="UTF-8"?>↵<bpmn2:definitions xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">↵  <bpmn2:process id="process1567044459787" name="流程1567044459787">↵    <bpmn2:documentation>描述</bpmn2:documentation>↵    <bpmn2:startEvent id="StartEvent_1" name="开始">↵      <bpmn2:outgoing>Flow_0n1hrs5</bpmn2:outgoing>↵    </bpmn2:startEvent>↵    <bpmn2:task id="Activity_1348ord">↵      <bpmn2:incoming>Flow_0n1hrs5</bpmn2:incoming>↵    </bpmn2:task>↵    <bpmn2:sequenceFlow id="Flow_0n1hrs5" sourceRef="StartEvent_1" targetRef="Activity_1348ord" />↵  </bpmn2:process>↵  <bpmndi:BPMNDiagram id="BPMNDiagram_1">↵    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="process1567044459787">↵      <bpmndi:BPMNEdge id="Flow_0n1hrs5_di" bpmnElement="Flow_0n1hrs5">↵        <di:waypoint x="220" y="82" />↵        <di:waypoint x="270" y="82" />↵      </bpmndi:BPMNEdge>↵      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">↵        <dc:Bounds x="184" y="64" width="36" height="36" />↵        <bpmndi:BPMNLabel>↵          <dc:Bounds x="191" y="40" width="22" height="14" />↵        </bpmndi:BPMNLabel>↵      </bpmndi:BPMNShape>↵      <bpmndi:BPMNShape id="Activity_1348ord_di" bpmnElement="Activity_1348ord">↵        <dc:Bounds x="270" y="42" width="100" height="80" />↵      </bpmndi:BPMNShape>↵    </bpmndi:BPMNPlane>↵  </bpmndi:BPMNDiagram>↵</bpmn2:definitions>↵`
const nodeTag = 'bpmn2:process'
const attr = 'name'
const start = xml.indexOf(nodeTag)
let attrValue = xml.substr(start, xml.indexOf('>', start))
attrValue = attrValue.substr(attrValue.indexOf(attr) + attr.length + 2)
attrValue = attrValue.substr(0, attrValue.indexOf('"'))
console.log(attrValue)
console.log(xml.indexOf('>'))
